services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - mongo

    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db # Persist MongoDB data

volumes:
    mongo_data:
