version: "3.8"
services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        depends_on:
            - mongo
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WDS_SOCKET_PORT=3000
        volumes:
            - ./client:/app
            - /app/node_modules
        command: npm start

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
